name: research_driven_time_scheduler_mobile_app
description: "A personalized time management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  
  # Calendar
  syncfusion_flutter_calendar: ^28.1.38
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/